apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  username: # add base 64 encoded username obtained from terminal
  password: # add base 64 encoded MONGO_INITDB_ROOT_PASSWORD obtained from terminal

## Apply the secret.yaml using kubectl apply to genereagte a secret file which is used in deployment file.
