---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            SecretKeyRef:
              name: wordpress-mysql
              Key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            SecretKeyRef:
              name: mysql-pass
              Key: password

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
